export const ADD_SUBREDDIT = 'ADD_SUBREDDIT'
export const ADD_TOP_POST = 'ADD_POST'
export const ADD_TODO = 'ADD_TODO'
export const SET_ERR = 'SET_ERR'
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD'
export const TOGGLE_TODO = 'TOGGLE_TODO'
