export const ADD_SUBREDDIT = 'ADD_SUBREDDIT'
export const ADD_TOP_POST = 'ADD_POST'
export const SET_ERR = 'SET_ERR'
export const SET_FETCH = 'SET_FETCH'
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD'
